[run]
enable_mpi = true

[dev_build]
compiler_name = 'g++'
optimization_level = '-O2'
switches = ''

[ground_truth]
compiler_name = 'g++'
optimization_level = '-O2'
switches = ''

[[compiler]]
binary = 'g++-7'
name = 'g++'
type = 'gcc'
optimization_levels = [
  '-O3',
]
switches_list = [
  '-freciprocal-math',
  '-funsafe-math-optimizations',
  '-mavx2 -mfma',
  ''
]

[[compiler]]
binary = 'clang++-6.0'
name = 'clang++'
type = 'clang'
optimization_levels = [
  '-O3',
]
switches_list = [
  '-freciprocal-math',
  '-funsafe-math-optimizations',
  ''
]

