#BHEADER**********************************************************************
# Copyright (c) 2008,  Lawrence Livermore National Security, LLC.
# Produced at the Lawrence Livermore National Laboratory.
# This file is part of HYPRE.  See file COPYRIGHT for details.
#
# HYPRE is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License (as published by the Free
# Software Foundation) version 2.1 dated February 1999.
#
# $Revision$
#EHEADER**********************************************************************


###############################################################################
##  All configurable variables are defined in the file named Makefile.config.in
##  When Autoconf is run, it will create a file named Makefile.config which
##  will have all of the configurable variables replaced with their values.
###############################################################################



srcdir = .
top_srcdir = ..
prefix = /uufs/chpc.utah.edu/common/home/u0692013/pearc_tutorial/hypre-2.10.0b/src/hypre
exec_prefix = ${prefix}



HYPRE_RELEASE_NAME    = hypre
HYPRE_RELEASE_VERSION = 2.11.2
HYPRE_RELEASE_DATE    = 2017/03/13
HYPRE_RELEASE_TIME    = 00:00:00
HYPRE_RELEASE_BUGS    = hypre-support@llnl.gov

HYPRE_SRC_TOP_DIR = /uufs/chpc.utah.edu/common/home/u0692013/pearc_tutorial/hypre-2.10.0b/src
HYPRE_BUILD_DIR   = /uufs/chpc.utah.edu/common/home/u0692013/pearc_tutorial/hypre-2.10.0b/src/hypre

HYPRE_INSTALL_DIR = NONE
HYPRE_LIB_INSTALL = ${exec_prefix}/lib
HYPRE_INC_INSTALL = ${prefix}/include

HYPRE_LIB_SUFFIX = .a

.SUFFIXES:
.SUFFIXES: .o .f .c .C .cxx .cc

.f.o:
	$(FC) $(FFLAGS) -c $< 
.c.o:
	$(CC) $(CFLAGS) -c $< 
.C.o:
	$(CXX) $(CXXFLAGS) -c $<
.cxx.o:
	$(CXX) $(CXXFLAGS) -c $<
.cc.o:
	$(CXX) $(CXXFLAGS) -c $<

FC       = 
FFLAGS   = -O  $(FC_COMPILE_FLAGS)

CC       = mpicc
CFLAGS   = -O2 -DHAVE_CONFIG_H $(C_COMPILE_FLAGS)

CXX      = mpiCC
CXXFLAGS = -O2 -DHAVE_CONFIG_H $(CXX_COMPILE_FLAGS)

LINK_FC  = 
LINK_CC  = mpicc
LINK_CXX = mpiCC

BUILD_FC_SHARED     = 
BUILD_CC_SHARED     = 
BUILD_CXX_SHARED    = 
SHARED_COMPILE_FLAG = 
SHARED_BUILD_FLAG   = 
SHARED_SET_SONAME   = 
SHARED_OPTIONS      = 

BUILD_PYTHON = 0
PYTHON       = 

BUILD_JAVA = 0

AR     = ar -rcu
RANLIB = ranlib

LDFLAGS = 
LIBS    =    -lstdc++ -lm 
FLIBS   = 

INCLUDES = 

##################################################################
##  LAPACK Library Flags 
##################################################################
HYPRE_LAPACK_SRC_DIR = /uufs/chpc.utah.edu/common/home/u0692013/pearc_tutorial/hypre-2.10.0b/src/lapack
HYPRE_LAPACK_FILES   = /uufs/chpc.utah.edu/common/home/u0692013/pearc_tutorial/hypre-2.10.0b/src/lapack/*.o
LAPACKLIBS           = 
LAPACKLIBDIRS        = 

##################################################################
##  BLAS Library Flags 
##################################################################
HYPRE_BLAS_SRC_DIR = /uufs/chpc.utah.edu/common/home/u0692013/pearc_tutorial/hypre-2.10.0b/src/blas
HYPRE_BLAS_FILES   = /uufs/chpc.utah.edu/common/home/u0692013/pearc_tutorial/hypre-2.10.0b/src/blas/*.o
BLASLIBS           = 
BLASLIBDIRS        = 

##################################################################
##  MPI options
##################################################################
MPIINCLUDE = 
MPILIBDIRS = 
MPILIBS    =  
MPIFLAGS   = 

##################################################################
##  Caliper options
##################################################################
CALIPER_INCLUDE = 
CALIPER_LIBS    = 

##################################################################
##  FEI options
##################################################################
HYPRE_FEI_SRC_DIR       = /uufs/chpc.utah.edu/common/home/u0692013/pearc_tutorial/hypre-2.10.0b/src/FEI_mv
HYPRE_FEI_BASE_DIR      = /uufs/chpc.utah.edu/common/home/u0692013/pearc_tutorial/hypre-2.10.0b/src/FEI_mv/fei-base
HYPRE_FEI_SUBDIRS       = femli SuperLU fei-hypre
HYPRE_FEI_SUPERLU_FILES = /uufs/chpc.utah.edu/common/home/u0692013/pearc_tutorial/hypre-2.10.0b/src/FEI_mv/SuperLU/SRC/*.o
HYPRE_FEI_HYPRE_FILES   = /uufs/chpc.utah.edu/common/home/u0692013/pearc_tutorial/hypre-2.10.0b/src/FEI_mv/fei-hypre/*.o
HYPRE_FEI_FEMLI_FILES   = /uufs/chpc.utah.edu/common/home/u0692013/pearc_tutorial/hypre-2.10.0b/src/FEI_mv/femli/*.o
