# This file is included by the generated Makefile.  If you have some things you
# want to change about the Makefile, it is best to do it here.

MFEM_SRC        = $(abspath ../mfem)
HYPRE_SRC       = $(abspath ../hypre-2.10.0b)
METIS_SRC       = $(abspath ../metis)

# source files to compile.
# Note:
#   until version 3.0, the wildcards *.cpp and tests/*.cpp are also in the
#   autogenerated Makefile.  If this breaks your setup, then you can override
#   and empty the SOURCE variable with
#     SOURCE   :=
#   then add in your own source files
SOURCE         += $(wildcard *.cpp)
SOURCE         += $(wildcard tests/*.cpp)

SOURCE         += $(wildcard ${MFEM_SRC}/fem/*.cpp)
SOURCE         += $(wildcard ${MFEM_SRC}/general/*.cpp)
SOURCE         += $(wildcard ${MFEM_SRC}/linalg/*.cpp)
SOURCE         += $(wildcard ${MFEM_SRC}/mesh/*.cpp)

# required compiler flags
# for example, include directories
#   CC_REQUIRED += -I<path>
# or defines
#   CC_REQUIRED += -DDEBUG_ENABLED=1
CC_REQUIRED    += -I${MFEM_SRC}
CC_REQUIRED    += -I${MFEM_SRC}/examples
CC_REQUIRED    += -isystem ${HYPRE_SRC}/src/hypre/include

# required linker flags
# for example, link libraries
#   LD_REQUIRED += -L<library-path> -l<library-name>
# or rpath
#   LD_REQUIRED += -Wl,-rpath=<abs-path-to-library-dir>
LD_REQUIRED    += -L${HYPRE_SRC}/src/hypre/lib -lHYPRE
LD_REQUIRED    += -L${METIS_SRC} -lmetis

# compiler and linker flags respectively - specifically for a dev build
# - DEV_CFLAGS:   non-recorded compiler flags (such as includes)
# - DEV_LDFLAGS:  linker flags (also not under test)
DEV_CFLAGS     +=
DEV_LDFLAGS    +=

# wrapper around the running of the test executable when run through the
# Makefile.
# For example, to run a test incorporating MPI, you could use
#   RUN_WRAPPER := srun --nodes 1
RUN_WRAPPER    :=

